# Please do not edit this file manually. If you want use your custom versions - change it in (.PACKAGE_USE_OVERRIDE)
COORDINATOR_VERSION="v2.0.4"
PROXY_VERSION="v2.0.2"
TRAEFIK_VERSION="v2.10.4"
PROMETHEUS_VERSION="v2.47.2"
GRAFANA_VERSION="10.0.3"
IPFS_VERSION="v0.20.0"
POSTGRES_VERSION="postgres:16-alpine" #OPTIONAL 12 by default
REDIS_VERSION="7-alpine"
