version: "3"

x-logging:
  &default-logging
  options:
    max-file: '1'
    compress: 'false'
  driver: local

networks:
  subquery_indexer:
    name: subquery_indexer
    external: true


services:
  haproxy_network_polygon:
    image: haproxytech/haproxy-alpine:${HAPROXY_VERSION:-2.9}
    container_name: haproxy_network_polygon
    restart: always
    networks:
      subquery_indexer:
        ipv4_address: ${DOCKER_SUBNET_PREFIX}.15
    entrypoint: "haproxy  -f /etc/haproxy/haproxy.cfg -f /etc/haproxy/config.d"
    expose:
      - "8385"
    volumes:
      - ./.data/haproxy/config.d:/etc/haproxy/config.d
      - ./.data/haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg
      - ./.data/haproxy/network_hostmapping.cfg:/etc/hosts