{
 "title": "Subquery indexer Heartbeat",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "availableProjects",
    "label": "List of projects",
    "query": {
     "query": "query_result(bash{env=\"indexer-projects\", exported_job=\"collect_projects_info\", instance=\"prometheus_bash_exporter:9300\", job=\"prometheus_bash_exporter\", verb=\"indexerStatus\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://subquery.network/assets/logo.eed034e5.svg\" />"
   }
  },
  {
   "title": "Indexer kSQT balance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kSQT" } },
   "targets": [
    {
     "expr": "bash{env=\"balance\",verb=\"indexer_balance\"} /1000000000000000000",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Operator MATIC balance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MATIC" } },
   "targets": [
    {
     "expr": "bash{env=\"balance\",verb=\"operator_balance\"} /1000000000000000000",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Coordinator version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "getServicesVersion",
     "endTimePath": "endTime",
     "queryText": "query  {\n  getServicesVersion {\n    coordinator\n  }\n}"
    }
   ]
  },
  {
   "title": "Proxy version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "getServicesVersion",
     "endTimePath": "endTime",
     "queryText": "query  {\n  getServicesVersion {\n    proxy\n  }\n}"
    }
   ]
  },
  {
   "title": "Total  Deployments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bash{env=\"indexer-summary\", exported_job=\"subquery_indexer_summary\", instance=\"prometheus_bash_exporter:9300\", job=\"prometheus_bash_exporter\", verb=\"total_deployments\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Agreements",
   "type": "timeseries",
   "description": "Count of Active Agreements",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 3 },
   "targets": [
    {
     "expr": "bash{env=\"indexer-summary\", exported_job=\"subquery_indexer_summary\", verb=\"count_active_paygs\"}",
     "legendFormat": "Number of  active Service Agreements (Payed plans)"
    }
   ]
  },
  {
   "title": "Self stake in kSQT",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kSQT" } },
   "targets": [
    {
     "expr": "bash{env=\"indexer-summary\", exported_job=\"subquery_indexer_summary\", job=\"prometheus_bash_exporter\", verb=\"self_stake\"}/1000000000000000009",
     "legendFormat": "Self stake"
    }
   ]
  },
  {
   "title": "Total stake kSQT",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kSQT" } },
   "targets": [
    {
     "expr": "bash{env=\"indexer-summary\", exported_job=\"subquery_indexer_summary\", job=\"prometheus_bash_exporter\", verb=\"total_stake\"}/1000000000000000009",
     "legendFormat": "Total stake"
    }
   ]
  },
  {
   "title": "Agreements",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bash{env=\"indexer-summary\", exported_job=\"subquery_indexer_summary\", instance=\"prometheus_bash_exporter:9300\", job=\"prometheus_bash_exporter\", verb=\"count_active_paygs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexer Payed Agreements",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "bash{env=\"indexer-projects\", exported_job=\"collect_projects_info\", instance=\"prometheus_bash_exporter:9300\", job=\"prometheus_bash_exporter\", verb=\"hasActivePayg\"}",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Indexers HEALTH",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bash{env=\"indexer-projects\", exported_job=\"collect_projects_info\", instance=\"prometheus_bash_exporter:9300\", job=\"prometheus_bash_exporter\", verb=\"indexerStatus\"}",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Summary indexer lastblock activity",
   "type": "timeseries",
   "description": "Network Lag",
   "gridPos": { "h": 7, "w": 7, "x": 2, "y": 11 },
   "targets": [
    {
     "expr": "bash{verb=\"processingTimeLag\"} /1000",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Indexer LAG",
   "type": "timeseries",
   "description": "Network Lag",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 11 },
   "targets": [
    {
     "expr": "bash{verb=\"syncLag\"}",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Query  HEALTH",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bash{env=\"indexer-projects\", exported_job=\"collect_projects_info\", instance=\"prometheus_bash_exporter:9300\", job=\"prometheus_bash_exporter\", verb=\"queryStatus\"}",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  { "title": "Alerting rules", "type": "alertlist", "gridPos": { "h": 8, "w": 7, "x": 16, "y": 17 } },
  {
   "title": "Projects Query Health",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 18 },
   "targets": [
    {
     "expr": "bash{env=\"indexer-projects\", exported_job=\"collect_projects_info\", instance=\"prometheus_bash_exporter:9300\", job=\"prometheus_bash_exporter\", verb=\"queryStatus\"}",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Projects Indexer Health",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 18 },
   "targets": [
    {
     "expr": "bash{env=\"indexer-projects\", exported_job=\"collect_projects_info\", instance=\"prometheus_bash_exporter:9300\", job=\"prometheus_bash_exporter\", verb=\"indexerStatus\"}",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Indexed project: $availableProjects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "repeat": "availableProjects"
  },
  {
   "title": "Query status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bash{deploymentId=\"${availableProjects}\", env=\"indexer-projects\", exported_job=\"collect_projects_info\", instance=\"prometheus_bash_exporter:9300\", job=\"prometheus_bash_exporter\", verb=\"queryStatus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexer status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bash{deploymentId=\"${availableProjects}\", env=\"indexer-projects\", exported_job=\"collect_projects_info\", instance=\"prometheus_bash_exporter:9300\", job=\"prometheus_bash_exporter\", verb=\"indexerStatus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexer LAG",
   "type": "stat",
   "description": "Network Lag",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bash{deploymentId=\"${availableProjects}\", env=\"indexer-projects\", exported_job=\"collect_projects_info\", job=\"prometheus_bash_exporter\", verb=\"syncLag\"}"
    }
   ]
  },
  {
   "title": "Indexer version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bash{deploymentId=\"${availableProjects}\", env=\"indexer-projects\", exported_job=\"collect_projects_info\", instance=\"prometheus_bash_exporter:9300\", job=\"prometheus_bash_exporter\", verb=\"indexerNodeVersion\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query gateway version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bash{deploymentId=\"${availableProjects}\", env=\"indexer-projects\", exported_job=\"collect_projects_info\", instance=\"prometheus_bash_exporter:9300\", job=\"prometheus_bash_exporter\", verb=\"queryNodeVersion\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexer LAG",
   "type": "timeseries",
   "description": "Network Lag",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "bash{deploymentId=\"${availableProjects}\", env=\"indexer-projects\", exported_job=\"collect_projects_info\", job=\"prometheus_bash_exporter\", verb=\"syncLag\"}",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "Query status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 29 },
   "targets": [
    {
     "expr": "bash{deploymentId=\"${availableProjects}\", env=\"indexer-projects\", exported_job=\"collect_projects_info\", instance=\"prometheus_bash_exporter:9300\", job=\"prometheus_bash_exporter\", verb=\"queryStatus\"}",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Lastblock activity",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "bash{deploymentId=\"${availableProjects}\", env=\"indexer-projects\", exported_job=\"collect_projects_info\", instance=\"prometheus_bash_exporter:9300\", job=\"prometheus_bash_exporter\", verb=\"processingTimeLag\"}\n",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  {
   "title": "Indexer status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 33 },
   "targets": [
    {
     "expr": "bash{deploymentId=\"${availableProjects}\",env=\"indexer-projects\", exported_job=\"collect_projects_info\", instance=\"prometheus_bash_exporter:9300\", job=\"prometheus_bash_exporter\", verb=\"indexerStatus\"}",
     "legendFormat": "{{displayName}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 6, "w": 2, "x": 0, "y": 37 } }
 ]
}