#!/bin/bash

ROOT_PATH=$( dirname -- "$( readlink -f -- "$0"; )"; );

if [ ! -f "${ROOT_PATH}/../.env" ]; then
    echo -e "\033[0;31m ✘ CRITICAl. \n env does not exists. Please rename .env.default to .env and set correct configuration. \033[0m"
    exit
fi

source $ROOT_PATH/../.env


echo -e "\033[0;33m ♨ Start & Update  Subquery indexer  \033[0m\n"

IP_PARTS=(${WIREGUARD_SUBNET//./ })
PRIVATE_NETWORK_IP="${IP_PARTS[0]}.${IP_PARTS[1]}.${IP_PARTS[2]}.1"
GATEWAY_IP_ADDRESS=$(/sbin/ip route | awk '/default/ { print $3 }')

DOCKER_SUBNET_PARTS=(${DOCKER_SUBNET_MASK//./ })
DOCKER_SUBNET_PREFIX="${DOCKER_SUBNET_PARTS[0]}.${DOCKER_SUBNET_PARTS[1]}.${DOCKER_SUBNET_PARTS[2]}"


export PRIVATE_NETWORK_IP=$PRIVATE_NETWORK_IP
export GATEWAY_IP_ADDRESS=$GATEWAY_IP_ADDRESS
export DOCKER_SUBNET_PREFIX=$DOCKER_SUBNET_PREFIX

# Prometheus configuration
for i in  $ROOT_PATH/../.data/prometheus/prometheus.conf.d/*.template
do
     cp -n -a  $i  ${i%%.template}
done

cp -n $ROOT_PATH/../.data/prometheus/prometheus.yml.template  $ROOT_PATH/../.data/prometheus/prometheus.yml
sed -i "s|bearer_token: ".*"|bearer_token: $PROMETHEUS_METRICS_TOKEN|" $ROOT_PATH/../.data/prometheus/prometheus.conf.d/query_count.yml

bash "${ROOT_PATH}/generate_prometheus_graphql_scrapers"

# Grafana
for i in  $ROOT_PATH/../.data/grafana/datasources/*.template
do
     cp -n -a  $i  ${i%%.template}
done


sed -i "s|Authorization: Bearer ".*"|Authorization: Bearer  $PROMETHEUS_METRICS_TOKEN|" $ROOT_PATH/../.data/grafana/datasources/prometheus.yml
sed -i  "s|password: ".*"|password: \"$DB_PASS\"|" $ROOT_PATH/../.data/grafana/datasources/indexer_postgres.yml


docker-compose -f $ROOT_PATH/../docker-compose-network.yml up -d

docker-compose -f $ROOT_PATH/../docker-compose-indexer.yml -f $ROOT_PATH/../docker-compose-monitoring.yml -f $ROOT_PATH/../docker-compose-privatenetwork.yml   up -d


echo -e "\033[0;33m ✈ Subquery indexer fully started  \033[0m\n"

if [ ! -f "${ROOT_PATH}/../SubqueryIndexerHandbook.tar.gz" ]; then
    bash $ROOT_PATH/generate_indexer_handbook
fi

