#!/bin/bash

ROOT_PATH=$( dirname -- "$( readlink -f -- "$0"; )"; );

set -a
source $ROOT_PATH/../.env
source $ROOT_PATH/../.PACKAGE_USE
set -a

echo -e "\033[0;33m ♨ Stopping Subquery indexer  \033[0m\n"


IP_PARTS=(${WIREGUARD_SUBNET//./ })
PRIVATE_NETWORK_IP="${IP_PARTS[0]}.${IP_PARTS[1]}.${IP_PARTS[2]}.1"

DOCKER_SUBNET_PARTS=(${DOCKER_SUBNET_MASK//./ })
DOCKER_SUBNET_PREFIX="${DOCKER_SUBNET_PARTS[0]}.${DOCKER_SUBNET_PARTS[1]}.${DOCKER_SUBNET_PARTS[2]}"

export PRIVATE_NETWORK_IP=$PRIVATE_NETWORK_IP
export DOCKER_SUBNET_PREFIX=$DOCKER_SUBNET_PREFIX

docker-compose -f ${ROOT_PATH}/../docker-compose-privatenetwork.yml -f ${ROOT_PATH}/../docker-compose-indexer.yml -f ${ROOT_PATH}/../docker-compose-monitoring.yml  down

docker-compose -f ${ROOT_PATH}/../docker-compose-network.yml down

echo -e "\n\n\n \033[0;33m ✔ Subquery indexer stopped  \033[0m\n"
