#!/bin/bash

set -a
source .PACKAGE_USE
source .PACKAGE_USE_OVERRIDE

INDEXER_COORDINATOR_RESULT=`curl  -s --compressed  'https://hub.docker.com/v2/repositories/subquerynetwork/indexer-coordinator/tags/?page_size=25&page=1&name&ordering' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'X-DOCKER-API-CLIENT: docker-hub/v3168.0.0' -H 'Connection: keep-alive' -H 'Referer: https://hub.docker.com/r/subquerynetwork/indexer-coordinator/tags'`
LATEST_COORDINATOR_VERSION=`echo $INDEXER_COORDINATOR_RESULT | jq ".results[0].name"`

INDEXER_PROXY_RESULT=`curl  -s --compressed  'https://hub.docker.com/v2/repositories/subquerynetwork/indexer-proxy/tags/?page_size=25&page=1&name&ordering' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'X-DOCKER-API-CLIENT: docker-hub/v3168.0.0' -H 'Connection: keep-alive' -H 'Referer: https://hub.docker.com/r/subquerynetwork/indexer-coordinator/tags'`
LATEST_PROXY_VERSION=`echo $INDEXER_PROXY_RESULT | jq ".results[0].name"`

echo "COORDINATOR $LATEST_COORDINATOR_VERSION \r\n"
echo "PROXY $LATEST_PROXY_VERSION \r\n"

echo "" > .PACKAGE_USE_OVERRIDE
echo "COORDINATOR_VERSION=$LATEST_COORDINATOR_VERSION" >> .PACKAGE_USE_OVERRIDE
echo "PROXY_VERSION=$LATEST_PROXY_VERSION" >> .PACKAGE_USE_OVERRIDE