#!/bin/bash
# Stop all containers by mask node_, query_ (per project)
docker container rm -f  $(docker container ls --all -q --filter name=node)
docker container rm -f $(docker container ls --all -q --filter name=query)